# Generated by Django 4.1.5 on 2023-02-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=10)),
                ('airline', models.CharField(max_length=2)),
                ('aircraft', models.CharField(max_length=10)),
                ('number', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
    ]
