# Generated by Django 4.1.5 on 2023-02-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('O', 'On-Time'), ('D', 'Delayed'), ('C', 'Cancelled')], default='O', max_length=1)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.flight')),
            ],
        ),
    ]
