# Generated by Django 4.1.5 on 2023-02-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(verbose_name='history date'),
        ),
        migrations.AddField(
            model_name='flight',
            name='toys',
            field=models.ManyToManyField(to='main_app.sub'),
        ),
    ]
