# Generated by Django 4.1.5 on 2023-02-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sub_alter_history_options_alter_history_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='toys',
            new_name='subs',
        ),
    ]
